problem:
  stack-trace: false
micronaut:
  serde:
    serialization:
      inclusion: ALWAYS
  application:
    name: oda-payment-service
  security:
    authentication: bearer
    token:
      bearer:
        enabled: true
      cookie:
        enabled: true
      jwt:
        signatures:
          jwks:
            keycloak:
              url: ${JWKS_URI}
  caches:
    jwks:
      expire-after-write: 240h
  http.services.yoomoney.url: https://api.yookassa.ru
  http.services.cryptocloud.url: https://api.cryptocloud.plus
  http.services.media.url: http://media-service/
  http.services.actions.url: http://actions-service/
  http.services.fundraising:
    url: https://yoomoney.ru
    follow-redirects: false
  http.services.robokassa.url: https://auth.robokassa.ru
endpoints:
  flyway:
    enabled: true
datasources:
  default:
    schema: 'payment'
flyway:
  datasources:
    default:
      enabled: true
      baseline-on-migrate: true
      schemas: 'payment'
      default-schema: 'payment'
jpa:
  default:
    entity-scan:
      packages: "io.github.opendonationassistant"
