package io.github.opendonationassistant.payment.notification;

import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;

public class WordFilter {

  public static List<String> banWords = new ArrayList<>();

  static {
    banWords.add("нига");
      banWords.add("дебильный");
      banWords.add("нигерами");
      banWords.add("нигга");
      banWords.add("ниггадяй");
      banWords.add("аутисты");
      banWords.add("инцелка");
      banWords.add("Аль Каида");
      banWords.add("Аль-Каида");
      banWords.add("хасбала");
      banWords.add("хызбала");
      banWords.add("петушара");
      banWords.add("петух");
      banWords.add("хохляндия");
      banWords.add("алькаида");
      banWords.add("черножопые");
      banWords.add("чернозадый");
      banWords.add("чернозадые");
      banWords.add("черномазые");
      banWords.add("черножопый");
      banWords.add("пидрожоп");
      banWords.add("пидрилы");
      banWords.add("пендос");
      banWords.add("пендосы");
      banWords.add("пидорасния");
      banWords.add("пендосия");
      banWords.add("пидорасия");
      banWords.add("н.и.г.е.р");
      banWords.add("негритосам");
      banWords.add("неграм");
      banWords.add("Putin");
      banWords.add("kill people");
      banWords.add("genocide");
      banWords.add("bombing");
      banWords.add("kneegear");
      banWords.add("гомосятник");
      banWords.add("гомосетник");
      banWords.add("гомосятина");
      banWords.add("пид0р");
      banWords.add("педрила");
      banWords.add("пидрила");
      banWords.add("negr");
      banWords.add("negr0");
      banWords.add("twat");
      banWords.add("poofter");
      banWords.add("cuckold");
      banWords.add("tard");
      banWords.add("дебила");
      banWords.add("дебилы");
      banWords.add("дебил");
      banWords.add("incels");
      banWords.add("pidorasy");
      banWords.add("pidoras");
      banWords.add("pidors");
      banWords.add("pidory");
      banWords.add("pidor");
      banWords.add("пизда");
      banWords.add("cunt");
      banWords.add("cuck");
      banWords.add("девственник");
      banWords.add("virgin");
      banWords.add("retard");
      banWords.add("ретард");
      banWords.add("нага");
      banWords.add("naga");
      banWords.add("allfaraby0");
      banWords.add("simp");
      banWords.add("чурки");
      banWords.add("гомосек");
      banWords.add("гомик");
      banWords.add("kike");
      banWords.add("жидов");
      banWords.add("жида");
      banWords.add("жиду");
      banWords.add("хача");
      banWords.add("incel");
      banWords.add("додик");
      banWords.add("куколд");
      banWords.add("куколда");
      banWords.add("елда");
      banWords.add("пидорас");
      banWords.add("хохлы");
      banWords.add("пидорами");
      banWords.add("пидора");
      banWords.add("пидору");
      banWords.add("хиджабу");
      banWords.add("даунами");
      banWords.add("хиджабами");
      banWords.add("хиджабы");
      banWords.add("неграми");
      banWords.add("негру");
      banWords.add("негром");
      banWords.add("хиджаба");
      banWords.add("хиджабе");
      banWords.add("пидоров");
      banWords.add("пидарасы");
      banWords.add("лохопедики");
      banWords.add("ПИДАРАС");
      banWords.add("хачик");
      banWords.add("хач");
      banWords.add("чурка");
      banWords.add("n1g");
      banWords.add("f@gg0ts");
      banWords.add("f@gg0t");
      banWords.add("fagg0ts");
      banWords.add("fagg0t");
      banWords.add("f@ggots");
      banWords.add("f@ggot");
      banWords.add("faggots");
      banWords.add("fags");
      banWords.add("f@g");
      banWords.add("faggot");
      banWords.add("fag");
      banWords.add("n1gguh");
      banWords.add("n1gguh1");
      banWords.add("n1ga");
      banWords.add("n1gga");
      banWords.add("n1gger");
      banWords.add("niga");
      banWords.add("nigrumps");
      banWords.add("nigrump");
      banWords.add("negroes");
      banWords.add("negros");
      banWords.add("negro");
      banWords.add("niggar");
      banWords.add("nigguh");
      banWords.add("nig");
      banWords.add("niggu");
      banWords.add("nigga");
      banWords.add("негр");
      banWords.add("негра");
      banWords.add("негры");
      banWords.add("негров");
      banWords.add("50541");
      banWords.add("sosal");
      banWords.add("nigger");
      banWords.add("сосал");
      banWords.add("симпы");
      banWords.add("симп");
      banWords.add("АУЕ");
      banWords.add("аутист");
      banWords.add("гидра");
      banWords.add("гитлер");
      banWords.add("даун");
      banWords.add("дауна");
      banWords.add("даунов");
      banWords.add("дауну");
      banWords.add("дауны");
      banWords.add("жид");
      banWords.add("дцп");
      banWords.add("жидяра");
      banWords.add("игил");
      banWords.add("инцел");
      banWords.add("ниггер");
      banWords.add("нигер");
      banWords.add("пiдор");
      banWords.add("педик");
      banWords.add("педики");
      banWords.add("педиков");
      banWords.add("пидар");
      banWords.add("пидер");
      banWords.add("Пидор@");
      banWords.add("пидор");
      banWords.add("пидр");
      banWords.add("талибан");
      banWords.add("хачи");
      banWords.add("хиджаб");
      banWords.add("хохол");
      banWords.add("廾仨广尸");
  }

  public static final String regex =
    "[-a-zA-Z0-9@:%._\\+~#=]{1,256}\\.[a-zA-Z0-9()]{1,6}\\b([-a-zA-Z0-9()@:%_\\+.~#?&//=]*)";
  public static final Pattern pattern = Pattern.compile(regex);

  public static String filter(String text) {
    for (String word : banWords) {
      text = text.replaceAll(word, "***");
    }
    text = pattern.matcher(text).replaceAll(" (ссылка удалена) ");
    text = text.replaceAll("https://", "").replaceAll("http://", "");
    return text;
  }
}
