name: Release

on:
  push:
    branches: [ "main" ]

permissions: write-all

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Analyze with Sonar
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: mvn -B -q verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar

    - name: Build service
      run: mvn -B -q clean package -Dpackaging=native-image -DskipTests

    - run: npm install
      working-directory: "target/generated-sources/openapi/"

    - uses: JS-DevTools/npm-publish@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        registry: "https://npm.pkg.github.com"
        package: "target/generated-sources/openapi/"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ghcr.io/opendonationassistant/oda-payment-service:${{ github.RUN_NUMBER }}
